### ISSUE TITLE
Strange error when calling SumReducer()

### ISSUE THREAD

**Issue by thriveth** [gcalderone/GFit.jl#2]
I am trying to use GModelFit to model emission lines in an astrophysical spectrum, but I am running into a strange issue, and I wonder if this is a bug or I am simply doing something wrong. 

My model is simply a number of Gaussian peaks at various wavelengths, defined on a Domain where I have checked the center and sigma are all well within the domain limits. I construct 17 Gaussian_1D components.

Non-workable code example:

```julia
dom = Domain{1}(wavelength)
complist = Vector{Symbol}()
components = Dict()

for l in line_names
    g = GModelFit.Gaussian_1D(norm, center, sigma)
    components[Symbol(l)] = g
    append!(complist, [Symbol(l)])
end

components[:total] = SumReducer(complist)
mod = Model(dom, components)
```
This code example is extracted from a larger, more complex code and I have not defined the trivial variables. The code above fails at the second-to-last line where the SumReducer is added, with the following error message:

```julia
ERROR: AssertionError: Domain dependencies must be listed first
Stacktrace:
 [1] dependencies(model::Model, cname::Symbol; select_domain::Bool)
   @ GModelFit ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:381
 [2] dependencies
   @ ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:371 [inlined]
 [3] update_step_init(model::Model)
   @ GModelFit ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:452
 [4] update!
   @ ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:398 [inlined]
 [5] setindex!(model::Model, comp::SumReducer, cname::Symbol)
   @ GModelFit ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:547
 [6] Model(domain::Domain{1}, args::Dict{Any, Any})
   @ GModelFit ~/.julia/packages/GModelFit/y04he/src/GModelFit.jl:326
 [7] build_model(domain::Domain{1}, neblines::DataFrame, redsh::Float64; fwhm_int::Float64, instrument::String, order::Int64, grism::String)
   @ Main ~/Arbejde/Projects/SunburstJWST/Code/MattsMuseMultifitter/matts_massive_muse_multifit_machine.jl:414
 [8] build_model(domain::Domain{1}, neblines::DataFrame, redsh::Float64)
   @ Main ~/Arbejde/Projects/SunburstJWST/Code/MattsMuseMultifitter/matts_massive_muse_multifit_machine.jl:364
 [9] top-level scope
   @ REPL[377]:1
```

The weird thing is that if:
- If I construct it with either of the line components individually, it works fine. 
- If I pass it as `SumReducer(complist[1:4])`, it works fine.
- If I construct it as `SumReducer(complist[5])`, it works fine.
- If I construct it as `SumReducer(complist[6:end])`, it works fine. 
- If I construct it as `SumReducer(last(complist, 12)`, it works fine. 
- If I construct it as `SumReducer(first(complist, 12)`, it fails. 

...And if I simply pass it the whole list, it fails, and I am tearing my hair out... 

There does not seem to be anything special about the 5th component in the list; if I leave it out and use the rest of the list, a similar problem still turns up. 

Am I doing something wrong, or is there a bug here?

**Comment by gcalderone** [comment]
Hi, sorry for the delay, I was on holidays...

The problem is likely due to the fact that you are using a `Dict`, which is not guaranteed to keep the insertion order while being explored with `iterate`.  As a consequence, when dependencies are being explored some component may not yet be defined.  Note that the actual order for `Dict` is not predictable, this is why you experience the problem with the 5th component.

To fix this simply use:
```
using DataStructures
components = OrderedDict()
```
in place of
```
components = Dict()
```

**Comment by thriveth** [comment]
Thank you for your reply! 

I got around the problem by instantiating the Model() with the mutually independent  line components in the the dict, then making sure I added the SumReducer component last. But the OrderedDict version looks like it could be interesting too.
